# Pre-commit hooks for repository-wide quality checks.
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c # v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: check-json
      - id: check-added-large-files
      - id: check-merge-conflicts

  - repo: https://github.com/NixOS/nixfmt
    rev: 81f20233e19adb967b0210e82206659e681f8712 # v1.1.0
    hooks:
      - id: nixfmt

  - repo: local
    hooks:
      - id: statix
        name: statix
        entry: statix check
        language: system
        types: [nix]
